config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'
  get 'pages/home'

  resources :artists do
    resources :songs
  end
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
  validates :describtion, presence: true, length: {maximum: 500}
  validates :country, presence: true, length: {maximum: 50}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: {maximum: 50}
  validates :album, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update]

  def index
    @artists = Artist.all
  end

  def show
    @photos = @artist.photos
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to @artist
    else
      render :new
    end
  end

  def edit
    @photos = @artist.photos
  end

  def update
    if @artist.update(artist_params)
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path, notice: "Artist deleted."
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end
    def image_params
      params[:images].present? ? params.require(:images) : []
    end
    def artist_params
      params.require(:artist).permit(:name, :describtion, :country)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @artist = photo.artist
    photo.destroy

    redirect_to edit_artist_path(@artist), notice: "Photo successfully removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
    @artist = params
  end

  def create
    @song = Song.new(song_params)
    @song.artist_id = params[:artist_id]

    if @song.save
      redirect_to artist_path(params[:artist_id])
    else
      render 'new'
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to artist_path(@song.artist), notice: "Song deleted."
  end

  private
    def song_params
      params.require(:song).permit(:name, :album, :release_date, :artist_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <% @artist.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, placeholder: "Name of the artist", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Country</label>
    <%= f.text_field :country, placeholder: "Country of origin", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Describtion</label>
    <%= f.text_area :describtion, placeholder: "Small text about the artist. (max 500 chars)", class: "form-control" %>
  </div>

  <label>Photos</label>
  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
    <div id="photos">
      <%= render 'photos/list' %>
    </div>

  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<%= render 'form' %>

app/views/artists/index.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name:</th>
        <th>Country:</th>
      </tr>
    </thead>
    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <th><%= link_to artist.name, artist %></th>
          <th><%= artist.country.capitalize %></th>
        </tr>
        <tr>
          <th><%= image_tag artist.photos.first.image.thumbnail %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to "New Artist", new_artist_url, class: "btn btn-default" %>

app/views/artists/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @artist.name %></div>

  <div class="panel-body">
    <p><%= @artist.describtion %></p>
    <p>
      <% @artist.photos.each do |photo| %>
        <%= image_tag photo.image.thumbnail %>
      <% end %>
    </p>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">Songs</div>

  <div class="panel panel-primary">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name:</th>
          <th>Album:</th>
          <th>Release Date:</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @artist.songs.each do |song| %>
          <tr>
            <th><%= song.name %></th>
            <th><%= song.album %></th>
            <th><%= song.release_date %></th>
            <th><%= link_to "Edit Song", edit_artist_song_url(@artist.id, song.id) %></th>
            <th><%= link_to "Delete Song", artist_song_url(@artist.id, song.id), method: :delete, data: { confirm: "Are you sure?" }%></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to "All Artists", artists_url, class: "btn btn-default" %>
<%= link_to "Add new Song",  new_artist_song_url(@artist.id), class: "btn btn-default" %>
<%= link_to "Edit Artist", edit_artist_url(@artist.id), class: "btn btn-default" %>
<%= link_to "Delete Artist", artist_url(@artist.id), method: :delete, data: { confirm: "Are you sure? \n All songs will be deleted too." }, class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <%= link_to "Delete", photo_path( photo.id ), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Codaisserify</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Artists</a></li>
          </ul>

        </div>
      </div>
    </div>

app/views/songs/_form.html.erb
<%= form_for @song, url: artist_songs_path do |f| %>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, placeholder: "Name of the song", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Album</label>
    <%= f.text_field :album, placeholder: "What album was it released from?", class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Release Date</label>
    <%= f.date_select :release_date %>

  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/songs/new.html.erb
<%= render 'form' %>

app/views/songs/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @song.name %></div>

  <div class="panel-body">
    <p><strong>Artist: </strong><%= @song.artist.name %>
    <p><strong>Album: </strong><%= @song.album %></p>
    <p><strong>Release Date: </strong><%= @song.release_date %></p>
  </div>
</div>
<%= link_to "Back to Artist", artist_url(@song.artist), class: "btn btn-default" %>
<%= link_to "Edit Song", edit_artist_song_url(@song.artist, @song), class: "btn btn-default" %>
<%= link_to "Delete Song", artist_song_url(@song.artist, @song), data: { confirm: "Are you sure?" },method: :delete, class: "btn btn-default" %>